create model and form UserNote
keder/togogit-site pull request #15
Opened 2020-10-23 21:08 UTC by katalinab95

2020-10-23 21:20 UTC, keder requested changes

2020-10-23 21:20 UTC, keder commented on notes/forms.py
> +        fields = '__all__'
Есть рекомендация оканчивать файл пустой строкой. Он подсветил даже. Это нужно потому что некоторые программы плохо понимают где конец файла: https://stackoverflow.com/a/729795

2020-10-23 21:20 UTC, keder commented on notes/models.py
> +    creation_time = models.CharField(max_length=64, null=True, default=datetime.date.today)
Аналогично

2020-10-23 22:34 UTC, mary-lev reviewed
Может быть, лучше назвать UserNoteForm? 
Ведь с помощью формы можно и редактировать?

2020-10-23 22:35 UTC, mary-lev commented on notes/models.py
> +    creation_time = models.CharField(max_length=64, null=True, default=datetime.date.today)
Как я поняла, creation_time должно быть DateTimeField, не CharField.

2020-10-23 22:46 UTC, katalinab95 commented on notes/models.py
> +    creation_time = models.CharField(max_length=64, null=True, default=datetime.date.today)
Под дата тайм надо настраивать тайм зону и вывод, проще использовать дейт тайм питоновский

2020-10-24 12:04 UTC, mary-lev commented on notes/models.py
> +    creation_time = models.CharField(max_length=64, null=True, default=datetime.date.today)
Не уверена, что это лучшее решение. И вывод, и зону можно настроить, а использование здесь CharField чревато дальнейшими непредсказуемыми сложностями.

2020-10-24 12:06 UTC, katalinab95 commented on notes/models.py
> +    creation_time = models.CharField(max_length=64, null=True, default=datetime.date.today)
Работала и работаю так и все норм

2020-10-25 09:31 UTC, closed without merging

2020-10-27 07:10 UTC, keder commented on notes/models.py
> +    creation_time = models.CharField(max_length=64, null=True, default=datetime.date.today)
Сделаю тикет на перевод в DateTime формат. Если мы планируем автоотправку уведомлений то нам в любом случае потребуется этот формат.